config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#landing"

  resources :shifts
  get 'shifts/day_log/:date', to: 'shifts#day_log'

  get 'clients/archived', to: 'clients#archived', as: :archived_clients
  put 'clients/archive/:id', to: 'clients#archive', as: :archive_client
  resources :clients

  get 'users/archived', to: 'users#archived', as: :archived_users
  put 'users/archive/:id', to: 'users#archive', as: :archive_user
  get 'users/:id/material/:material_id', to: 'users#material', as: :edit_user_material
  patch 'users/:id/material/:material_id', to: 'users#update_user_material', as: :update_user_material
  resources :users

  resources :materials
  resources :material_dates
  
  get 'invoices/archive', to: 'invoices#archive'
  resources :invoices do
    resources :invoice_dates, shallow: true do 
      resources :shift_dates
      # resources :material_dates
    end
  end

  # get 'completed', to: 'tasks#completed', as: :completed_tasks
  # get '/invoices/:id/pdf', to: 'invoices#set_pdf', as: 'invoice_set_pdf'

  
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :client
    has_many :invoice_dates, dependent: :destroy
    has_many :shift_dates, through: :invoice_dates
    has_many :material_dates, through: :invoice_dates

    def just_date
        return created_at.to_s.slice(0, 10)
    end

    def current_total
        total = 0
        invoice_ids = InvoiceDate.where(invoice_id: self.id)
        invoice_ids.each do |i|
            total += i.material_sub_2(i.id) 
            total += i.shift_sub_2(i.id)
        end
        return total
    end   

    def labor_total(id)
        l_total = 0
        invoice_ids = InvoiceDate.where(invoice_id: id)
        invoice_ids.each do |i|
            l_total += i.shift_sub_2(i.id)
        end
        return l_total
    end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @invoices = Invoice.where(active: true)
    end

    def show
        @invoice = Invoice.find(params[:id])
        @invoice_dates = @invoice.invoice_dates.sort_by &:date
        
        respond_to do |format|
            format.html
            format.pdf do
              pdf = InvoicePdf.new(@invoice)
              total_update = @invoice.current_total
              @invoice.update(total_cost: total_update)
              send_data pdf.render, filename: 'HGInvoice.pdf', type: 'application/pdf'
            end
        end
    end

    def new
        @invoice = Invoice.new
    end

    def create
        @invoice = Invoice.create(invoice_params)

        if @invoice.save
            flash[:notice] = "Invoice successfully created"
            redirect_to "/invoices"
        else
            flash[:error] = "We an encountered an error creating your invoice"
            render 'new'
        end
    end

    def archive
        @invoices = Invoice.where(active: false)
    end

    # def edit
    # end

    def update
        @invoice = Invoice.find(params[:id])

        if @invoice.active == true
            respond_to do |format|
                if @invoice.update(active: false)
                    flash.now[:notice] = "Invoice archived successfully"
                    format.html { redirect_to invoices_path, notice: "Invoice archived succesfully"}
                    format.js {}
                else
                    flash.now[:error] = "Error archiving invoice"
                    format.html { redirect_to invoices_path, error: "Error achiving invoices"}
                    format.js { }
                end
            end
        else
            respond_to do |format|
                if @invoice.update(active: true)
                    flash.now[:notice] = "Invoice unarchived successfully"
                    format.html { redirect_to invoices_path, notice: "Invoice archived succesfully"}
                    format.js {}
                else
                    flash.now[:error] = "Error unarchiving invoice"
                    format.html { redirect_to invoices_path, error: "Error achiving invoices"}
                    format.js {}
                end
            end
        end
    end

    def destroy
        @invoice = Invoice.find(params[:id])
        if @invoice.destroy
            flash.now[:notice] = "Invoice successfully deleted"
        else
            flash.now[:error] = "Error deleting invoice"
        end
    end

private
    def invoice_params
        params.require(:invoice).permit(:client_id, :master_desc, :total_cost, :active);
    end

end

app/helpers/invoices_helper.rb
module InvoicesHelper

    def invoice_enders
        if @invoice.active == true
            render partial: "invoices/archive_buttons"            
        else
            render partial: "invoices/unarchive_buttons"
        end
    end

end

app/views/invoices/_active-invoices.html.erb
<% @invoices.each do |i| %>
    <tr id="invoice-<%= i.id %>">
        <td><%= i.client.full_name %></td>
        <td><%= i.client.address %></td>
        <td><%= i.created_at %></td>
        <td><%= i.total_cost %></td>
        <td><%= link_to 'View', invoice_path(i) %></td>
        <td><%= link_to 'Delete', invoice_path(i),
              method: :delete, remote:true,
              data: { confirm: 'Are you sure? This cannot be reversed.' } %></td>
    </tr>
<% end %>

app/views/invoices/_active_invoices.html.erb
<% @invoices.each do |i| %>
    <tr id="invoice-<%= i.id %>">
        <td><%= i.client.full_name %></td>
        <td class="hide-table-col"><%= i.client.address %></td>
        <td><%= i.created_at.strftime("%m-%d-%Y") %></td>
        <td class="hide-table-col">$ <%= i.current_total %></td>
        <td class="options-col center-col"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, invoice_path(i), class: "btn btn-sm btn-dark" %> | 
        <span class="hide-table-col"><%= link_to '<i class="fas fa-folder-minus"></i>'.html_safe, invoice_path(i), class: "btn btn-sm btn-warning", remote: true, method: :patch, data: { confirm: 'Are you sure you want to archive this record?' } %> | </span> 
        <%= link_to 'X', invoice_path(i),
              method: :delete, remote:true,
              data: { confirm: 'Are you sure? This cannot be reversed.' }, class: "btn btn-sm btn-danger" %></td>
    </tr>
<% end %>

app/views/invoices/_archive_buttons.html.erb
<%= link_to 'Add Date', new_invoice_invoice_date_path(@invoice), remote:true, class: "btn btn-success", id: "add-button-target" %>
<a href="/invoices/<%=@invoice.id%>.pdf" target="_blank" class="btn btn-danger ml-2">Finalize + PDF</a>
<%= link_to 'Archive <i class="fas fa-folder-minus"></i>'.html_safe, invoice_path(@invoice), class: "btn btn-secondary ml-2", remote: true, method: :patch, data: { confirm: 'Are you sure you want to archive this record?' } %>

app/views/invoices/_archived_invoices.html.erb
<% @invoices.each do |i| %>
    <tr id="invoice-<%= i.id %>">
        <td><%= i.client.full_name %></td>
        <td class="hide-table-col"><%= i.client.address %></td>
        <td><%= i.created_at.strftime("%m-%d-%Y") %></td>
        <td class="hide-table-col">$ <%= i.current_total %></td>
        <td class="center-col options-col"><%= link_to '<i class="far fa-eye"></i>'.html_safe, invoice_path(i), class: "btn btn-sm btn-dark" %> | 
        <%= link_to '<i class="fas fa-folder-open"></i>'.html_safe, invoice_path(i), class: "btn btn-sm btn-warning", remote: true, method: :patch, data: { confirm: 'Are you sure you want to unarchive this record?' } %></td>
    </tr>
<% end %>

app/views/invoices/_unarchive_buttons.html.erb
<%= link_to 'Add Date', new_invoice_invoice_date_path(@invoice), remote:true, class: "btn btn-success", id: "add-button-target" %>
<a href="/invoices/<%=@invoice.id%>.pdf" target="_blank" class="btn btn-danger ml-2">Generate PDF</a>
<%= link_to 'Unarchive <i class="fas fa-folder-plus"></i>'.html_safe, invoice_path(@invoice), class: "btn btn-warning ml-2", remote: true, method: :patch, data: { confirm: 'Are you sure you want to archive this record?' } %>

app/views/invoices/archive.html.erb
<div class="client-user-header mt-md-3 mt-2">
    <h2>Archives</h2>
    <%= link_to 'Back to Active', invoices_path, class: "btn btn-dark ml-3" %>
</div>
<div>
    <table id="datatable" data-turbolinks="false" class="display">
        <thead>
            <th>Client</th>
            <th class="hide-table-col">Address</th>
            <th>Start Date</th>
            <th class="hide-table-col">Total</th>
            <th class="center-col"></th>
        </thead>
        <tbody>
            <%= render 'archived_invoices'%>
        <tbody>
    </table>
</div>

app/views/invoices/destroy.js.erb
$("#invoice-<%= @invoice.id %>").fadeOut(300)
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');

app/views/invoices/index.html.erb
<div class="client-user-header mt-md-3 mt-2">
    <h2>Active Invoices</h2>
    <%= link_to 'Add New', new_invoice_path, class: "btn btn-success" %>
</div>
<div>
    <table id="datatable" data-turbolinks="false" class="display">
        <thead>
            <th>Client</th>
            <th class="hide-table-col">Address</th>
            <th>Created</th>
            <th class="hide-table-col">Current Total</th>
            <th class="options-col center-col"></th>
        </thead>
        <tbody>
            <%= render 'active_invoices'%>
        <tbody>
    </table>
</div>
<br>
<%= link_to 'View Archives', invoices_archive_path, class: "btn btn-warning ml-3 archive-button" %>
            

app/views/invoices/new.html.erb
<div class="col-md-8 col-11 mx-auto bg-white border rounded border-secondary pl-5 pr-5 pt-4 pb-3 mt-md-4 mt-5">
    <h2>New Invoice</h2>
    <%= form_for @invoice, local: true do |form| %>
        <div class="form-group">
            <label>Client: </label>
            <%= collection_select(:invoice, :client_id, client_shift_attach, :id, :full_name, {}, {:class=>'form-control'}) %>
        </div>
        <div class="form-group">
            <label>Description: (optional)</label>
            <%= form.text_area :master_desc, placeholder: "Enter a short description", class: "form-control" %>
        <%= form.submit "Submit", :id=>'invoice-submit', class: "btn btn-dark mt-4" %>
    <% end %>
</div>

app/views/invoices/show.html.erb
<div class="invoice-header container mt-3 bg-white p-4 p-md-5 rounded-top border border-bottom-0 border-bottom-md-0 border-secondary ">
    <div class="row justify-content-between">
        <div class="invoice-client-info col-md-9">
            <h3><%= @invoice.client.full_name %></h3>
            <%= @invoice.client.address%><br>
            <%= number_to_phone(@invoice.client.home_phone, area_code: true) %><br>
            <%= @invoice.client.email %>
        </div>
        <div class="col-md-3 mt-4">
            <p><strong>Invoice #: </strong><%= @invoice.id %><br>
            <strong>Date: </strong><%= @invoice.created_at.strftime("%m-%d-%Y") %></p>
        </div>
    </div>
    <div class="mt-md-3">
        <p class="mb-md-0"><em><%= @invoice.master_desc %></em></p>
    </div>
</div>
<div class="bg-white">
    <div class="description-header">
        <h4>Description</h4>
    </div>
    <div class="invoice-date-master col-md-10 m-md-auto">
        <%= render partial: 'invoice_dates/invoice_date', collection: @invoice_dates %>
        <div id="ender_buttons" class="row no-gutter mb-3 mt-3 mx-auto">
            <%= invoice_enders %>
        </div>
    </div>
</div>

app/views/invoices/update.js.erb
<%# CURRENTLY ON ARCHIVES POSTS %>
if (document.getElementById("invoice-<%= @invoice.id %>")) {
    $('#invoice-<%= @invoice.id %>').fadeOut(250);
} else {
    $(window.location.replace("/invoices"))
}
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');