config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#landing"

  resources :shifts
  get 'shifts/day_log/:date', to: 'shifts#day_log'

  get 'clients/archived', to: 'clients#archived', as: :archived_clients
  put 'clients/archive/:id', to: 'clients#archive', as: :archive_client
  resources :clients

  get 'users/archived', to: 'users#archived', as: :archived_users
  put 'users/archive/:id', to: 'users#archive', as: :archive_user
  get 'users/:id/material/:material_id', to: 'users#material', as: :edit_user_material
  patch 'users/:id/material/:material_id', to: 'users#update_user_material', as: :update_user_material
  resources :users

  resources :materials
  resources :material_dates
  
  get 'invoices/archive', to: 'invoices#archive'
  resources :invoices do
    resources :invoice_dates, shallow: true do 
      resources :shift_dates
      # resources :material_dates
    end
  end

  # get 'completed', to: 'tasks#completed', as: :completed_tasks
  # get '/invoices/:id/pdf', to: 'invoices#set_pdf', as: 'invoice_set_pdf'

  
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :invoices, dependent: :restrict_with_error
    has_many :shifts, dependent: :restrict_with_error
    has_one_attached :house_pic

    validates_presence_of :first_name, message: "Enter a first name"
    validates_presence_of :last_name, message: "Enter a last name"
    validates_presence_of :address, message: "Enter an address"

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :authenticate_user!
    before_action :all_clients, only: [:index, :create, :update, :destroy]

    def index
    end

    def show
        @client = Client.find(params[:id])
    end

    def new
        @client = Client.new
    end

    def edit
        @client = Client.find(params[:id])
    end

    def create
        @client = Client.create(client_params)
        
        respond_to do |format|
            if @client.save
                format.html { redirect_to clients_path, notice: "Client added successfully" }
                flash.now[:notice] = "Client added successfully."
                format.js {}
            else
                format.html { render 'new', error: "Errors saving your client"}
                flash.now[:error] = "Errors saving your client."
                format.js { render 'new' }
            end
        end
    end

    def archive
        @client = Client.find(params[:id])

        if @client.is_active == true
            respond_to do |format|
                if @client.update_attribute(:is_active, false)
                    flash.now[:notice] = 'Client archived successfully'
                    format.html { redirect to clients_path, notice: "Client archived succesfully"}
                    format.js {}
                else
                    flash.now[:error] = "Error archiving client"
                    format.html { redirect_to clients_path, error: "Error achiving client"}
                    format.js {}
                end
            end
        else
            respond_to do |format|
                if @client.update_attribute(:is_active, true)
                    flash.now[:notice] = "Client unarchived successfully"
                    format.html { redirect_to clients_path, notice: "Client archived succesfully"}
                    format.js {}
                else
                    flash.now[:error] = "Error unarchiving invoice"
                    format.html { redirect_to clients_path, error: "Error achiving client"}
                    format.js {}
                end
            end
        end
    end

    def archived
        @clients = Client.where(is_active: false)
    end

    def update
        @client = Client.find(params[:id])

        respond_to do |format|
            if @client.update(client_params)
                flash.now[:notice] = "Client updated successfully."
                format.html { redirect_to clients_path, notice: "Client updated successfully" }
                format.js {}
            else
                flash.now[:error] = "Errors editting your client"
                format.html { render "new", error: "Errors editting your client" }
                format.js { render 'edit' }
            end
        end
    end

    def destroy
        @client = Client.find(params[:id])

        if @client.destroy
            flash.now[:notice] = "Client successfully deleted"
        else
            flash.now[:error] = @client.errors.full_messages[0]
            render 'update'
        end
    end

private

    def all_clients
        @clients = Client.where(is_active: true)
    end
    
    def client_params
        params.require(:client).permit(:first_name, :last_name, :address, :email, :home_phone, :cell_phone, :house_pic, :is_active);
    end

end

app/helpers/clients_helper.rb
module ClientsHelper

    def house_pic_choice
        if @client.house_pic.attached?
            return (image_tag @client.house_pic, options = {width: "100%"})
        else
            return (image_tag "home_placeholder.jpg", options = {width: "100%", class: "house-pic-container"})
        end
    end
    
end

app/views/clients/_archive_client_list.html.erb
<table id="datatable" data-turbolinks="false" class="display">
    <thead>
        <tr class="table-header">
            <th>First Name</th>
            <th>Last Name</th>
            <th class="hide-table-col">Email</th>
            <th class="hide-table-col">Address</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% clients.each do |c| %>
            <tr id="client-<%= c.id %>">
                <td><%= c.first_name %></td>
                <td><%= c.last_name %></td>
                <td class="hide-table-col"><%= c.email %></td>
                <td class="hide-table-col"><%= c.address %></td>
                <td class="center-col options-col"><%= link_to '<i class="far fa-eye"></i>'.html_safe, client_path(c), class: "btn btn-sm btn-dark" %> | 
                <%= link_to '<i class="fas fa-folder-plus"></i>'.html_safe, archive_client_path(c), method: :put, class: "btn btn-sm btn-warning", remote: true, data: { confirm: 'Are you sure you want to unarchive this record?' } %>
                <span class="hide-table-col"> | <%= link_to 'X', client_path(c),
                    method: :delete,
                    data: { confirm: 'Are you sure? This cannot be reversed.' }, class: "btn btn-sm btn-danger" %></span></td> 
            </tr>
        <% end %>
    </tbody>
</table>

app/views/clients/_client_card.html.erb
<h2><%= @client.full_name %></h2>
<hr class="my-4">
<p><strong>Email:</strong> <%= @client.email %></p>
<p><strong>Address:</strong> <%= @client.address %></p>
<p><strong>Home Phone:</strong> <%= number_to_phone(@client.home_phone, area_code: true) %></p>
<p><strong>Cell Phone:</strong> <%= number_to_phone(@client.cell_phone, area_code: true) %></p>
<%= link_to 'Edit', edit_client_path(@client), remote:true, class: "btn btn-sm btn-success" %>
<%= link_to 'Delete', client_path(@client),
            method: :delete, remote: true,
            data: { confirm: 'Are you sure? This cannot be reversed.' }, class: 'btn btn-sm btn-danger' %>

app/views/clients/_client_list.html.erb
<table id="datatable" data-turbolinks="false" class="display">
    <thead>
        <tr class="table-header">
            <th>First Name</th>
            <th>Last Name</th>
            <th class="center-col hide-table-col">Email</th>
            <th class="center-col hide-table-col">Address</th>
            <th class="options-col center-col"></th>
        </tr>
    </thead>
    <tbody>
        <% clients.each do |c| %>
            <tr id="client-<%= c.id %>">
                <td><%= c.first_name %></td>
                <td><%= c.last_name %></td>
                <td class="hide-table-col"><%= c.email %></td>
                <td class="hide-table-col"><%= c.address %></td>
                <td class="options-col"><%= link_to '<i class="far fa-eye"></i>'.html_safe, client_path(c), class: "btn btn-sm btn-dark" %> | 
                <%= link_to '<i class="fas fa-folder-minus"></i>'.html_safe, archive_client_path(c), method: :put, class: "btn btn-sm btn-warning", remote: true, data: { confirm: 'Are you sure you want to archive this record?' } %> 
                <span class="hide-table-col"> | <%= link_to 'X', client_path(c),
                    method: :delete, remote:true,
                    data: { confirm: 'Are you sure? This cannot be reversed.' }, class: "btn btn-sm btn-danger" %></span></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/clients/_edit.html.erb
<div>
    <div class="close-container"><a class="close-x">&times;</a></div>
    <h2>Edit</h2>
    <%= form_for @client, remote: true do |form| %>

        <%= form_group_for form, :first_name, label: false do %>
            <label>First Name: </label>
            <%= form.text_field :first_name, placeholder: "First Name", class: 'form-control form-control-sm' %>
        <% end %>

        <%= form_group_for form, :last_name, label: false do %>
            <label>Last Name: </label>
            <%= form.text_field :last_name, placeholder: "First Name", class: 'form-control form-control-sm' %>
        <% end %>

        <%= form_group_for form, :address, label: false do %>
            <label>Address: </label>
            <%= form.text_field :address, placeholder: "Address", class: "form-control form-control-sm" %>
        <% end %>
        
        <div class="form-group">
            <label>Email: </label>
            <%= form.text_field :email, placeholder: "Email", class: "form-control form-control-sm" %>
        </div>
        <div class="form-group">
            <label>Home Phone: </label>
            <%= form.telephone_field :home_phone, placeholder: "Home Phone", class: "form-control form-control-sm" %>
        </div>
        <div class="form-group">
            <label>Cell Phone: </label>
            <%= form.telephone_field :cell_phone, placeholder: "Cell Phone", class: "form-control form-control-sm" %>
        </div>
        <div class="form-group">
            <label>House Photo:</label>
            <%= form.file_field :house_pic, class: "form-control form-control-sm" %>
        </div>
        <%= form.submit "Submit", :id=>'hours-submit', onclick: "showLoad()", class: "btn btn-sm btn-dark" %>
    <% end %>
</div>
<div class="spinner" style="display: none">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>

app/views/clients/_shifts.html.erb
<table id="datatable" data-turbolinks="false" class="display">
    <thead>
        <th>Date</th>
        <th>Employees</th>
        <th>Hours</th>
        <th>Labor Cost</th>
    </thead>
    <tbody>
        <% client.shifts.each do |i| %>
            <tr id="invoice-<%= i.id %>">
                <td><%= i.start_time.strftime("%m-%d-%Y") %></td>
                <td><%= i.employee_count %></td>
                <td><%= i.time_elapsed %></td>
                <td><%= number_to_currency(i.earned) %></td>
            </tr>
        <% end %>
    <tbody>
</table>
            

app/views/clients/archive.js.erb
if (document.getElementById("client-<%= @client.id %>")) {
    $('#client-<%= @client.id %>').fadeOut(250);
} else {
    $(window.location.replace("/clients"))
}

$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');

app/views/clients/archived.html.erb
<div class="client-user-header mt-md-3">
    <h2>Client Archive</h2>
    <%= link_to 'Back to Clients', clients_path, class: "btn btn-dark" %>
</div>

<div id="client-list-div">
    <%= render partial: "archive_client_list", locals: {clients: @clients} %>
</div>

app/views/clients/create.js.erb
$("#client-add").empty();
$('#flash').html('<%= j render partial: "layouts/flash_messages"%>');
$("#client-list-div").html('<%= j render partial: 'client_list', locals: {clients: @clients} %>')
datatableInit();
$('.client-user-header').show()
$('#client-list-div').show()

app/views/clients/destroy.js.erb
$('#client-<%= @client.id %>').fadeOut(150);
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');

app/views/clients/edit.js.erb
$('.invoice-block').hide();
$(".id-card").html("<%= j (render 'edit') %>");
$('#flash').html('<%= j render partial: "layouts/flash_messages"%>');

$(document).on("touchend click", ".close-x", function(){
    $(".id-card").html("<%= j (render 'client_card') %>");
    $('.invoice-block').show();
});

app/views/clients/index.html.erb
<div id="client-add">
</div>

<div class="client-user-header mt-md-3">
    <h2>Clients</h2>
    <%= link_to 'Add New', new_client_path, remote: true, class: "btn btn-sm btn-success" %>
</div>

<div id="client-list-div">
    <%= render partial: "client_list", locals: {clients: @clients} %>
    <%= link_to 'View Archives', archived_clients_path, class: "btn btn-warning mb-3 ml-3 archive-button" %>
</div>

app/views/clients/new.js.erb
$('.client-user-header').hide()
$('#client-list-div').hide()
$('#flash').html('<%= j render partial: "layouts/flash_messages"%>');
$("#client-add").html("<%= j (render 'form') %>");
$("#close-div").trigger("create")

$(document).on("touchend click", ".close-x", function(){
    $('.client-user-header').show()
    $('#client-list-div').show()
    $("#client-add").empty()
});

app/views/clients/show.html.erb
<div class="row no-gutters mt-md-4 justify-content-around">  
   <div class="col-md-5 id-card p-4 p-md-5">
      <%= render "client_card" %>
   </div>

   <div class="col-md-5 house-pic-outer">
      <%= house_pic_choice %>
   </div>
</div>

<div class="mt-4 col-md-12 mx-md-auto invoice-block">
   <%= render partial: "shifts", locals: {client: @client} %>
</div>

app/views/clients/update.js.erb
$(".id-card").html("<%= j (render 'client_card') %>");
$(".house-pic-outer").html("<%= j (render partial: 'house_pic', locals: {client: @client}) %>");
$('.invoice-block').show();
$('#flash').html('<%= j render partial: "layouts/flash_messages"%>');