config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#landing"

  resources :shifts
  get 'shifts/day_log/:date', to: 'shifts#day_log'

  get 'clients/archived', to: 'clients#archived', as: :archived_clients
  put 'clients/archive/:id', to: 'clients#archive', as: :archive_client
  resources :clients

  get 'users/archived', to: 'users#archived', as: :archived_users
  put 'users/archive/:id', to: 'users#archive', as: :archive_user
  get 'users/:id/material/:material_id', to: 'users#material', as: :edit_user_material
  patch 'users/:id/material/:material_id', to: 'users#update_user_material', as: :update_user_material
  resources :users

  resources :materials
  resources :material_dates
  
  get 'invoices/archive', to: 'invoices#archive'
  resources :invoices do
    resources :invoice_dates, shallow: true do 
      resources :shift_dates
      # resources :material_dates
    end
  end

  # get 'completed', to: 'tasks#completed', as: :completed_tasks
  # get '/invoices/:id/pdf', to: 'invoices#set_pdf', as: 'invoice_set_pdf'

  
end

app/models/shift.rb
class Shift < ApplicationRecord
    belongs_to :client
    has_one :shift_date
    has_one :invoice_date, through: :shift_date

    validates_numericality_of :employee_count, greater_than: 0, message: "Must be a whole number greater than 0"
    
    def time_elapsed
        return ((end_time - start_time)/60/60)
    end

    def just_date
        return start_time.to_s.slice(5, 6)
    end

    def simple_start
        return start_time.to_s[11..15]
    end

    def simple_end
        return end_time.to_s[11..15]
    end

    def full_name_hours
        return self.user.first_name + ' ' + self.user.last_name + ' - ' + self.time_elapsed.to_s
    end

    def self.earned_plus_create(sp)
        earned_plus(sp)
    end

    def earned_update(sp)
        earned_up(sp)
    end

    private

    def self.earned_plus(sp)
        sclone = sp.clone()
        sclone["earned"] = ((Time.zone.parse(sclone["end_time"]) - Time.zone.parse(sclone["start_time"]))/60/60) * sclone["employee_count"].to_f * 25
        $shift = Shift.create(sclone)
    end

    # def self.multi(sp)
    #     if sp["user_id"].kind_of?(Array)
    #         sp["user_id"].each do |u|
    #             sclone = sp.clone()
    #             sclone["user_id"] = u
    #             sclone["earned"] = ((Time.zone.parse(sclone["end_time"]) - Time.zone.parse(sclone["start_time"]))/60/60) * User.find(sclone["user_id"]).hourly_rate
    #             $shift = Shift.create(sclone)
    #         end
    #     else 
    #         sp["earned"] = ((Time.zone.parse(sp["end_time"]) - Time.zone.parse(sp["start_time"]))/60/60) * User.find(sp["user_id"]).hourly_rate
    #         $shift = Shift.create(sp)
    #     end
    # end

    def earned_up(sp)
        sclone = sp.clone()
        sclone["earned"] = ((Time.zone.parse(sclone["end_time"]) - Time.zone.parse(sclone["start_time"]))/60/60) * sclone["employee_count"].to_f * 25
        self.update(sclone)
    end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    before_action :authenticate_user!
    def index
        if current_user.role == "Admin" || current_user.role == "Foreman"
            @shifts = Shift.all
            $client_name_toggle = false
        else
            @shifts = Shift.where(user_id: current_user.id)
        end
    end

    def show
        @shift = Shift.find(params[:id])
        authorize @shift
    end

    def day_log
        date = Date.parse(params[:date])

        if current_user.role == "Admin" || current_user.role == "Foreman"
            @shifts = Shift.where(start_time: date.all_day)
            @material_dates = MaterialDate.where(date: date)
            @client_materials = MaterialDate.client_tally(@material_dates, date)
        else
            @shifts = Shift.where(start_time: date.all_day).where(user_id: current_user.id)
            @material_dates = MaterialDate.where(date: date, user_id: current_user.id)
            @client_materials = MaterialDate.client_tally(@material_dates, date)
        end
    end

    def new
        @shift = Shift.new
    end

    def edit
        @shift = Shift.find(params[:id])
    end

    def create
        @shift = Shift.earned_plus_create(shift_params)
        @shifts = Shift.all

        respond_to do |format|
            if $shift.save
                format.html { redirect_to shifts_path, notice: "Shift(s) logged successfully."}
                flash.now[:notice] = "Shift(s) logged successfully."
                format.js {}
            else
                format.html { render 'new', error: "Error logging your hours."}
                flash.now[:error] = "Error logging your hours"
                format.js {render 'new'}
            end
        end
    end

    def update
        @shift = Shift.find(params[:id])

        authorize @shift

        if @shift.earned_update(shift_params)
            flash[:notice] = "Shift updated successfully."
            redirect_to "/shifts"
        else
            flash[:error] = "Error updating your shift"
            render 'edit'
        end
    end

    def destroy
        @shift = Shift.find(params[:id])
        authorize @shift

        if @shift.destroy
            flash[:notice] = "Shift successfully deleted."
            redirect_to '/shifts'
          else
            flash.now[:alert] = "There was an error deleting the shift."
            redirect_to '/shifts'
          end
    end

private
    
    def shift_params
        params.require(:shift).permit(:start_time, :end_time, :earned, :client_id, :employee_count, :user_id);
    end

end

app/helpers/shifts_helper.rb
module ShiftsHelper

    def options_for_active_users
        options_from_collection_for_select(User.where(is_active: true).order('last_name ASC'), "id", "full_name")
    end

    def shift_create_access
        if current_user.role == "Worker"
            render partial: 'shifts/worker_form'
        elsif current_user.role == "Designer"
            render partial: 'shifts/designer_form'
        else
            render partial: 'shifts/foreman_form'
        end
    end

    def shift_house_pic_choice
        if @shift.client.house_pic.attached?
            return (image_tag @shift.client.house_pic, options = {width: "100%"})
        else
            return (image_tag "home_placeholder.jpg", options = {width: "100%", class: "house-pic-container"})
        end
    end

end

app/views/shifts/_card.html.erb
<div class="shift-card">
  <div class="shift-card-body align-middle">
    <div class="close-container"><a class="close-x">&times;</a></div>
    <h4 class="card-title"><span class="date-code"><%= @shift.start_time.strftime("%m/%d") %></span> <%= @shift.client.full_name %></h4>
    <p style="font-size: 75%"><%= @shift.client.address %></p>
    <hr class="my-2">
    <% if current_user.role != "Designer" %>
    <strong># of Employees: </strong><%= @shift.employee_count %><br>
    <% end %>
    <strong>Start: </strong><%= @shift.start_time.strftime("%I:%M %p") %><br>
    <strong>End: </strong><%= @shift.end_time.strftime("%I:%M %p") %><br>
    <strong>Total Hours: </strong><%= @shift.time_elapsed %><br>
    <strong>Total Earnings: </strong><%= number_to_currency(@shift.earned) %></p>

    <% if policy(@shift).update? %>
      <%= link_to 'Edit', edit_shift_path, remote: true, class: "btn btn-sm btn-success" %>
    <% end %>
    <%= link_to 'Delete', shift_path, method: :delete, class: "btn btn-sm btn-danger" %>
  </div>
  <div class="shift-image-container mt-2">
    <%= shift_house_pic_choice %>
  </div>
</div>

app/views/shifts/_day_log_list_none.html.erb
<div>
    <h3 class="pl-4"> Shifts </h3>
    <table class="table">
        <thead>
            <th>Client</th>
            <th>Worker</th>
            <th>Hours</th>
            <th><%= link_to '+', new_shift_path, remote: true, class: "btn btn-sm btn-success float-right" %></th>
        </thead>
    </table>

    <div class="none-message">
        <p> There's nothing here.<br>Add a shift.</p>
    </div>
</div>

app/views/shifts/_day_materials_list.html.erb
<div class="pt-3">
    <h3 class="pl-4"> Materials </h3>
    <table class="display table" id="datatable2">
        <thead>
            <tr>
                <th>Client</th>
                <th>Total Cost</th>
                <th>Total Charge</th>
                <th><%= link_to '+', new_material_date_path, remote: true, class: "btn btn-sm btn-success float-right" %></th>
            </tr>
        </thead>
        <tbody>
            <% @client_materials.each do |m| %>
                <tr>
                
                    <% if current_user.address_view %>
                    <td><%= m[:client_address] %></td>
                    <% else %>
                    <td><%= m[:client_full_name] %></td>
                    <% end %>

                    <td><%= number_to_currency(m[:total_cost]) %></td>
                    <td><%= number_to_currency(m[:total_charge]) %></td>
                    <td><%= link_to '<i class="far fa-eye"></i>'.html_safe, material_date_path(id: m[:client_id], date: m[:date]), remote: true, class: "btn tablebtn btn-sm btn-dark" %>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/shifts/_day_materials_list_none.html.erb
<div class="pt-3">
    <h3 class="pl-4"> Materials </h3>
    <table class="table">
        <thead>
            <tr>
                <th>Material</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Charge</th>
                <th><%= link_to '+', new_material_date_path, remote: true, class: "btn btn-sm btn-success float-right" %></th>
            </tr>
        </thead>
    </table>

    <div class="none-message">
        <p> There's nothing here.<br>Add a material.</p>
    </div>
</div>

app/views/shifts/_designer_form.html.erb
<%= form_for @shift, remote: true do |form| %>
    <div class="form-group">
        <label>Client: </label>
        <% if current_user.address_view %>
        <%= collection_select(:shift, :client_id, client_shift_attach, :id, :address, {}, {:class=>'form-control'}) %>
        <% else %>
        <%= collection_select(:shift, :client_id, client_shift_attach_names, :id, :full_name, {}, {:class=>'form-control'}) %>
        <% end %>  
    </div>
    <div class="form-group">
        <label>Start Time: </label>
        <%= form.datetime_field :start_time, placeholder: "Start Time", :id => 'start_time', class: "form-control" %>
    </div>
    <%= form_group_for form, :end_time, label: false do %>
        <label>End Time: </label>
        <%= form.datetime_field :end_time, placeholder: "End Time", :id => 'end_time', class: "form-control" %>
    <% end %>
    <%= form.hidden_field :user_id, value: "#{current_user.id}", class: "form-control" %>
    <%= form.hidden_field :employee_count, value: 1, class: "form-control" %>
    <%= form.submit "Submit", :id=>'hours-submit', class: "btn btn-dark" %>
<% end %>

app/views/shifts/_edit.html.erb
<div class="close-container"><a class="close-x">&times;</a></div>
<%= form_for @shift do |form|%>
    <h2>Edit Shift</h2>
    <div class="form-group">
        <label>Client: </label>
        <%= collection_select(:shift, :client_id, Client.all, :id, :full_name, {}, {:class=>'form-control form-control-sm'}) %>
    </div>
    <div class="form-group">
        <label># of Employees: </label>
        <%= form.number_field :employee_count, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Start Time: </label>
        <%= form.datetime_field :start_time, placeholder: "Start Time", :id => 'start_time', class: "form-control form-control-sm" %>
    </div>
    <div class="form-group">
        <label>End Time: </label>
        <%= form.datetime_field :end_time, placeholder: "End Time", :id => 'end_time', class: "form-control form-control-sm" %>
    </div>
    <%= form.submit "Submit", :id=>'hours-submit', class: "btn btn-sm btn-dark" %>
<% end %>

app/views/shifts/_foreman_form.html.erb
<%= form_for @shift, remote: true do |form| %>
    <div class="form-group">
        <label>Client: </label>
        <% if current_user.address_view %>
        <%= collection_select(:shift, :client_id, client_shift_attach, :id, :address, {}, {:class=>'form-control'}) %>
        <% else %>
        <%= collection_select(:shift, :client_id, client_shift_attach_names, :id, :full_name, {}, {:class=>'form-control'}) %>
        <% end %>   
    </div>
    <div class="form-group">
        <label># of Employees: </label>
        <%= form.number_field :employee_count, value: 1, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Start Time: </label>
        <%= form.datetime_field :start_time, placeholder: "Start Time", :id => 'start_time', class: "form-control" %>
    </div>
    <%= form_group_for form, :end_time, label: false do %>
        <label>End Time: </label>
        <%= form.datetime_field :end_time, placeholder: "End Time", :id => 'end_time', class: "form-control" %>
    <% end %>
    <%= form.hidden_field :user_id, value: "#{current_user.id}", class: "form-control" %>
    <%= form.submit "Submit", :id=>'hours-submit', class: "btn btn-dark" %>
<% end %>

app/views/shifts/_form.html.erb
<div id="active-shift-add">
    <div class="close-container"><a class="close-x">&times;</a></div>
    <h4>Add Hours</h4>
    <%= shift_create_access %>
</div>

app/views/shifts/_materials_form.erb
<%= form_for @material_dates, remote: true do |form| %>
    
    <div class="form-group">
        <label><%= %></label>
        <%= collection_select(:shift, :client_id, client_shift_attach, :id, :address, {}, {:class=>'form-control'}) %>
    </div>

    <div class="form-group">
        <label>Employees: </label>
        <%= select_tag "shift[user_id]", options_for_active_users, multiple: true, class: "form-control" %>
    </div>
    <div class="form-group">
        <label>Start Time: </label>
        <%= form.datetime_field :start_time, placeholder: "Start Time", :id => 'start_time', class: "form-control" %>
    </div>
    <%= form_group_for form, :end_time, label: false do %>
        <label>End Time: </label>
        <%= form.datetime_field :end_time, placeholder: "End Time", :id => 'end_time', class: "form-control" %>
    <% end %>
    <%= form.submit "Submit", :id=>'hours-submit', class: "btn btn-dark" %>
<% end %>

app/views/shifts/_shift_cal.html.erb
<%= month_calendar events: shifts do |date, shifts| %>
    <a href="/shifts/day_log/<%= date %>" data-remote="true" class="shift-check">
    <%= date.day %>
    </a>
    <%# REMOVED SHIFT VIZ %>
<% end %>

<script>
$('.shift-check').click(function(e) {
    $('.shift-check').removeClass('date-circle');
    $(this).addClass('date-circle');
    var target = $(e.target);
    var targetDate = target.attr("href").slice(-10);
    sessionStorage.setItem("date", targetDate);
});
</script>

app/views/shifts/_worker_form.html.erb
<%= form_for @shift, remote: true do |form| %>
    <div class="form-group">
        <label>Client: </label>
        <%= collection_select(:shift, :client_id, client_shift_attach, :id, :full_name, {}, {:class=>'form-control'}) %>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
        <label>Start Time: </label>
        <%= form.datetime_field :start_time, placeholder: "Start Time", :id => 'start_time', class: "form-control" %>
    </div>
    <%= form_group_for form, :end_time, label: false do %>
        <label>End Time: </label>
        <%= form.datetime_field :end_time, placeholder: "End Time", :id => 'end_time', class: "form-control" %>
    <% end %>
    <%= form.submit "Submit", :id=>'hours-submit', class: "btn btn-dark" %>
<% end %>

app/views/shifts/create.js.erb
$("#add-form").empty().hide();
$("#calendar-container").html("<%= j (render "shift_cal", shifts: @shifts) %>")
$("#calendar-container").show();
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');

app/views/shifts/day_log.js.erb
$("#add-form").empty().css("display", "none");
$("#day-log-container").empty();

<% if @shifts.length >= 1 %>
    $("#day-log-container").append("<%= j (render 'day_log_list') %>")
<% else %>
    $("#day-log-container").append("<%= j (render 'day_log_list_none') %>")
<% end %>

<% if @material_dates.length >= 1 %>
    $("#day-log-container").append("<%= j (render 'day_materials_list') %>")
<% else %>
    $("#day-log-container").append("<%= j (render 'day_materials_list_none') %>")
<% end %>

$("#day-log-container").css("display", "flex");

$("#day-log-toggle").css("display", "block");

$(document).ready( function () {
    $('#datatable').DataTable( {
        "paging": false,
        "info": false,
        "bLengthChange": false,
        "searching": false,
        columnDefs: [
            { orderable: false, targets: -1 },
         ],
        "initComplete": function(){ 
            $("#datatable").show(); 
            }
    } );
    
    $('#datatable2').DataTable( {
        "paging": false,
        "searching": false,
        "info": false,
        "bLengthChange": false,
        columnDefs: [
            { orderable: false, targets: -1 },
         ],
        "initComplete": function(){ 
            $("#datatable2").show(); 
            }
    } );
} );

app/views/shifts/index.html.erb
<div class="row no-gutters">
  <div id="calendar-container" class="col-lg-5">
    <%= render "shift_cal", shifts: @shifts %>
  </div>

  <div id="add-form" class="col-md-7 col-12" style="display:none;">
  </div>

  <div id="day-log-container" class="col-lg-7 col-12" style="display:none;">
  </div>
</div>