config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations] 
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#landing"

  resources :shifts
  get 'shifts/day_log/:date', to: 'shifts#day_log'

  get 'clients/archived', to: 'clients#archived', as: :archived_clients
  put 'clients/archive/:id', to: 'clients#archive', as: :archive_client
  resources :clients

  get 'users/archived', to: 'users#archived', as: :archived_users
  put 'users/archive/:id', to: 'users#archive', as: :archive_user
  get 'users/:id/material/:material_id', to: 'users#material', as: :edit_user_material
  patch 'users/:id/material/:material_id', to: 'users#update_user_material', as: :update_user_material
  resources :users

  resources :materials
  resources :material_dates
  
  get 'invoices/archive', to: 'invoices#archive'
  resources :invoices do
    resources :invoice_dates, shallow: true do 
      resources :shift_dates
      # resources :material_dates
    end
  end

  # get 'completed', to: 'tasks#completed', as: :completed_tasks
  # get '/invoices/:id/pdf', to: 'invoices#set_pdf', as: 'invoice_set_pdf'

  
end

app/models/invoice_date.rb
class InvoiceDate < ApplicationRecord
    belongs_to :invoice
    has_many :shift_dates, dependent: :destroy
    has_many :material_dates, dependent: :destroy

    def just_date
        return created_at.to_s.slice(0, 10)
    end

    def shift_sub_2(id)
        shift_total = 0
        shift_dates = ShiftDate.where(invoice_date_id: id)
        shift_dates.each do |shift|
            shift_total += shift.shift.earned
            # shift_total += shift.earned
        end
        return shift_total
    end

    def material_sub_2(id)
        mat_total = 0
        material_dates = MaterialDate.where(invoice_date_id: id)
        material_dates.each do |mat|
            mat_total += mat.cost
        end
        return mat_total
    end

    def daily_total(id)
        return self.material_sub_2(id) + self.shift_sub_2(id)
    end
end

app/controllers/invoice_dates_controller.rb
class InvoiceDatesController < ApplicationController
    before_action :authenticate_user!
    def show
        @invoice_date = InvoiceDate.find(params[:id])
        @shift_dates = @invoice_dates.shift_dates
    end
    
    def new
        @invoice = Invoice.find(params[:invoice_id])
        @invoice_date = InvoiceDate.new
    end

    def create
        @invoice_date = InvoiceDate.create(invoice_date_params)

        if @invoice_date.save
            flash.now[:notice] = "Date created successfully"
        else
            flash.now[:error] = "Error adding new date"
            render 'new'
        end
    end

    def destroy
        @invoice_date = InvoiceDate.find(params[:id])
        if @invoice_date.destroy
            flash.now[:notice] = "Date successfully deleted"
        else
            flash.now[:error] = "Error deleting shift"
        end
    end

private
    def invoice_date_params
        params.require(:invoice_date).permit(:invoice_id, :date, :description, :subtotal);
    end
end

app/helpers/invoice_dates_helper.rb
module InvoiceDatesHelper
    def shift_dates_to_select
        Shift.where(just_date = @invoice_date.date.to_s)
    end
end

app/views/invoice_dates/_daily_total.html.erb
<td><strong>Daily Total:</strong></td>
<td></td>
<td><strong><%= number_to_currency(invoice_date.daily_total(invoice_date.id)) %></strong></td>
<td></td>

app/views/invoice_dates/_invoice_date.html.erb
<div class="invoice-date-card" id="invoice-card-<%= invoice_date.id %>">
    <div class="close hide-button"><i class="fas fa-chevron-circle-up"></i></div>
   
   <h4 class="header-date"><%= invoice_date.date.strftime("%m-%d-%Y") %></h4>
    <p class="pl-2"><%= invoice_date.description %></p>
    
<%# DAILY SHIFT CONTAINER %>

    <div id="invoice-shift-container-<%= invoice_date.id %>" class="invoice-clip-container">
        <div class="d-flex align-items-baseline">
            <h5 class="col-3">Shifts</h5>
            <%= link_to 'Add', new_invoice_date_shift_date_path(invoice_date), remote:true, class: "btn-sm btn-success offset-2 offset-lg-0 shift-add-btn" %>
        </div>
        <div id="invoice-shift-listings-<%= invoice_date.id %>">
            <table class="table table-striped">
                <thead>
                    <th>Name</th>
                    <th>Hours</th>
                    <th>Total</th>
                    <th></th>
                </thead>
                <tbody id="tbody-shift-<%= invoice_date.id%>">
            <% invoice_date.shift_dates.each do |shift_date| %>
                    <%= render "invoice_dates/shift_date_instant", shift_date: shift_date %>
            <% end %>
                    <tr id="tbody-shift-<%= invoice_date.id %>-total" class="total-row">
                        <%= render "invoice_dates/shift_date", invoice_date: invoice_date %>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="invoice-shift-form-<%= invoice_date.id%>">
        </div>
    </div>
    
<%# DAILY MATERIALS CONTAINER %>    
    
    <div id="invoice-material-container-<%= invoice_date.id %>" class="invoice-clip-container">
        <div class="d-flex align-items-baseline">
            <h5 class="col-3">Materials</h5><%= link_to 'Add', new_invoice_date_material_date_path(invoice_date), remote:true, class: "btn-sm btn-success offset-2 offset-lg-0 material-add-btn" %>
        </div>
        <div id="invoice-material-listings-<%= invoice_date.id %>">
            <table class="table table-striped">
                <thead>
                    <th>Type</th>
                    <th>Cost</th>
                    <th>Total</th>
                    <th></th>
                </thead>
                <tbody id="tbody-material-<%= invoice_date.id%>">
            <% invoice_date.material_dates.each do |mat_date| %>
                    <%= render "invoice_dates/material_date_instant", mat_date: mat_date %>
            <% end %>
                    <tr id="tbody-material-<%= invoice_date.id %>-total" class="total-row">
                        <%= render "invoice_dates/material_date", invoice_date: invoice_date %>
                    </tr>
                    <tr id="tbody-daily-total-<%= invoice_date.id %>" class="daily-total-row">
                        <%= render "invoice_dates/daily_total", invoice_date: invoice_date %>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="invoice-material-form-<%= invoice_date.id%>">
        </div>
    </div>


    <%= link_to 'Delete', invoice_date_path(invoice_date), method: :delete, remote:true, data: { confirm: 'Are you sure? This cannot be undone.' }, class: "btn-sm btn-danger button-target" %>
</div>

app/views/invoice_dates/_invoice_date_form.html.erb
<div id="invoice-form-container" class="col-md-10 mx-auto mt-3">
    <div class="close-container"><a class="close-x">&times;</a></div>
    <h2>Add Date</h2>
    <%= form_for [@invoice, @invoice_date], remote: true do |form| %>
        <div class="form-group">
            <label>Date: </label>
            <%= form.date_field :date, :value => Time.now.strftime("%Y-%m-%d"), class: "form-control" %>
        </div>
        <div><%= form.hidden_field :invoice_id, :value => @invoice.id, id: "invoice-id-fill" %></div>
        <div class="form-group">
            <label>Description: </label>
            <%= form.text_field :description, placeholder: "Short description of the work (optional)", class: "form-control" %>
        </div>
        <%= form.submit "Submit", :id=>'invoice-date-submit', class: "btn btn-dark" %>
    <% end %>
</div>

app/views/invoice_dates/_material_date.html.erb
<td><strong>Subtotal</strong></td>
<td></td>
<td><%= number_to_currency(invoice_date.material_sub_2(invoice_date.id)) %></td>
<td></td>

app/views/invoice_dates/_material_date_instant.html.erb
<tr id="material-date-<%= mat_date.id %>">
    <td><%= mat_date.material.name %></td>
    <td><%= number_to_currency(mat_date.true_cost) %> x <%= mat_date.quantity %></td>
    <td><%= number_to_currency(mat_date.cost) %></td>
    <td><%= link_to 'X', material_date_path(mat_date),
        method: :delete, remote:true,
        data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
</tr>

app/views/invoice_dates/_shift_date.html.erb
<td><strong>Subtotal</strong></td>
<td></td>
<td><%= number_to_currency(invoice_date.shift_sub_2(invoice_date.id)) %></td>
<td></td>

app/views/invoice_dates/_shift_date_instant.html.erb
<tr id="shift-date-<%= shift_date.id %>">
    <td><%= shift_date.shift.user.full_name %></td>
    <td><%= shift_date.shift.time_elapsed %></td>
    <td><%= number_to_currency(shift_date.shift.earned) %></td>
    <td><%= link_to 'X', shift_date_path(shift_date),
        method: :delete, remote:true,
        data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
</tr>

app/views/invoice_dates/create.js.erb
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');
$("#invoice-form-container").remove();
$(".invoice-date-master").show();
$("#add-button-target").before("<%= j render :partial => 'invoice_dates/invoice_date', :locals => { :invoice_date => @invoice_date } %>");

app/views/invoice_dates/destroy.js.erb
$('#invoice-card-<%= @invoice_date.id %>').fadeOut(300);
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');

app/views/invoice_dates/new.js.erb
$('#flash').html('<%= j render partial: "layouts/flash_messages" %>');
$(".invoice-date-master").hide().after("<%= j (render 'invoice_date_form') %>")

$(document).on("touchend click", ".close-x", function(){
    $("#invoice-form-container").remove();
    $(".invoice-date-master").show();
});